FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_APP_NAME
ARG VITE_API_BASE_URL
ARG VITE_API_KEY
ARG VITE_DEFAULT_THEME
ARG VITE_AI_ADVISOR_URL
ARG VITE_AI_ADVISOR_MODE
ARG VITE_AI_ADVISOR_API_NAME

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_KEY=$VITE_API_KEY
ENV VITE_DEFAULT_THEME=$VITE_DEFAULT_THEME
ENV VITE_AI_ADVISOR_URL=$VITE_AI_ADVISOR_URL
ENV VITE_AI_ADVISOR_MODE=$VITE_AI_ADVISOR_MODE
ENV VITE_AI_ADVISOR_API_NAME=$VITE_AI_ADVISOR_API_NAME

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]