services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_DEFAULT_THEME: ${VITE_DEFAULT_THEME}
        VITE_AI_ADVISOR_URL: ${VITE_AI_ADVISOR_URL}
        VITE_AI_ADVISOR_MODE: ${VITE_AI_ADVISOR_MODE}
        VITE_AI_ADVISOR_API_NAME: ${VITE_AI_ADVISOR_API_NAME}

    container_name: fund_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - fund_network

networks:
  fund_network:
    external: true
    name: fund-be_fund_network