services:
  frontend:
    build:
      context: .
      env_file:
        - .env

    container_name: fund_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - fund_network

networks:
  fund_network:
    external: true
    name: fund-be_fund_network